## Preprocesamiento de la data

### Carga de las librerías y delos módulos

In [40]:
import sys
from pathlib import Path
import numpy as np

sys.path.append(str(Path.cwd().parent))

In [2]:
import pandas as pd
import importlib

from src import load
from src import feature_engineering

In [3]:
importlib.reload(load)
importlib.reload(feature_engineering)

### Integración de los datos de todos los indicadores

In [4]:
anios=range(2022,2027)

In [5]:
datasets_anuales=[]
for i in anios:
    indicadores=load.procesar_indicadores(i, load.archivos,load.meses, load.columnas_indicadores)
    lista_cartera=load.procesar_cartera(i, load.archivos,load.meses)
    indicadores_cartera=feature_engineering.feature_engineering_cartera(lista_cartera)
    lista_indicadores_y_cartera=feature_engineering.unir_todos_indicadores(indicadores, indicadores_cartera)
    indicadores_y_cartera=pd.concat(lista_indicadores_y_cartera,
        ignore_index=True)
    datasets_anuales.append(indicadores_y_cartera)

In [6]:
dataset_indicadores_cartera = pd.concat(
    datasets_anuales,
    ignore_index=True
)

In [7]:
dataset_indicadores_cartera

,MES,AÑO,ENTIDAD,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6),INDICE DE CAPITALIZACION NETO: FK / FI,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO,MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO,MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO,...,GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3),RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO,RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO,CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO),FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO,CARTERA IMPRODUCTIVA / CARTERA BRUTA,CARTERA VENCIDA / CARTERA BRUTA,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,CARTERA REFINANCIADA / CARTERA BRUTA,CARTERA REESTRUCTURADA / CARTERA BRUTA
0,Enero,2022,BP GUAYAQUIL,4.141498,0.084334,0.14544,0.85456,1.20628,0.01425,0.022054,...,0.015297,0.128519,0.012238,0.880435,0.21366,0.012428,0.005401,0.007027,0.015168,0.004739
1,Enero,2022,BP PACIFICO,2.6451,0.097085,0.223376,0.77662,1.10437,0.032261,0.034234,...,0.009043,0.102842,0.012095,0.854694,0.341741,0.031243,0.015333,0.015910,0.109175,0.039099
2,Enero,2022,BP PICHINCHA,-23.726736,0.092786,0.093155,0.90684,1.43429,0.032347,0.045745,...,0.011048,0.113642,0.011441,0.830851,0.178394,0.028914,0.007745,0.021169,0.029904,0.055667
3,Enero,2022,BP PRODUBANCO,3.21609,0.0715,0.144305,0.85569,1.43589,0.032538,0.032279,...,0.010637,0.127418,0.010326,0.86819,0.320233,0.015483,0.003208,0.012275,0.007283,0.026373
4,Enero,2022,BP AUSTRO,1.391251,0.078349,0.167015,0.83298,1.05067,0.073443,0.016077,...,0.010616,0.035847,0.003303,0.671742,0.250919,0.039514,0.014388,0.025126,0.079909,0.026752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,Julio,2026,BP CAPITAL,0.743608,0.088779,0.203118,0.796882,0.974991,0.035269,0,...,0.022017,0.000602,0.00008,0.762553,0.241408,0.043296,0.002111,0.041185,0.014315,0.002475
1300,Julio,2026,BP DELBANK,7.435204,0.288765,0.157979,0.842021,1.769811,0.105913,0.000002,...,0.040853,-0.003508,-0.001117,1.275196,0.591112,0.031132,0.010960,0.020171,0.068912,0.003849
1301,Julio,2026,BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.,0.788369,0.055191,0.128191,0.871809,0.96599,0.000358,0,...,0.030823,0.00906,0.000702,0.535486,0.331037,0.021523,0.009165,0.012358,0.028839,0.007510
1302,Julio,2026,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",2.990621,0.103658,0.105249,0.894751,1.069191,0.079619,0.006083,...,0.021339,0.024556,0.0029,0.954322,0.17721,0.099170,0.040266,0.058904,0.041134,0.006622
1303,Julio,2026,BP VISIONFUND ECUADOR S.A.,21.25641,0.128662,0.037131,0.962869,1.177842,0.008478,0,...,0.04589,0.244274,0.034437,2.064977,0.426914,0.044672,0.022074,0.022598,0.007556,0.000656

In [8]:
dataset_indicadores_cartera["ENTIDAD"].unique()

array(['BP GUAYAQUIL', 'BP PACIFICO', 'BP PICHINCHA', 'BP PRODUBANCO',
       'BP AUSTRO', 'BP BOLIVARIANO', 'BP CITIBANK', 'BP DINERS',
       'BP GENERAL RUMIÑAHUI', 'BP INTERNACIONAL', 'BP LOJA',
       'BP MACHALA', 'BP SOLIDARIO', 'BP PROCREDIT', 'BP AMAZONAS',
       'BP BANCO COMERCIAL DE MANABI', 'BP LITORAL', 'BP COOPNACIONAL',
       'BP CAPITAL', 'BP FINCA S.A./BANCO AMIBANK S.A.', 'BP DELBANK',
       'BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.',
       'BP BANCO  DESARROLLO DE LOS PUEBLOS  S.A., CODESARROLLO',
       'BP VISIONFUND ECUADOR S.A.'], dtype=object)

In [9]:
dataset_indicadores_cartera[dataset_indicadores_cartera["ENTIDAD"]=="BANCO AMIBANK S.A., EN LIQUIDACION"]

Empty DataFrame
Columns: [MES, AÑO, ENTIDAD, ( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6), INDICE DE CAPITALIZACION NETO: FK / FI, ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS, ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS, ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO, MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO, MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO, MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO, MOROSIDAD DE LA CARTERA TOTAL, COBERTURA DE LA CARTERA REFINANCIADA, COBERTURA DE LA CARTERA REESTRUCTURADA, COBERTURA DE LA CARTERA PROBLEMÁTICA, GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO PROMEDIO (3), GASTOS DE OPERACION  / MARGEN FINANCIERO, GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3), RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO, RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO, CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO), FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO, CARTERA IMPRODUCTIVA / CARTERA BRUTA, CARTERA VENCIDA / CARTERA BRUTA, CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA, CARTERA REFINANCIADA / CARTERA BRUTA, CARTERA REESTRUCTURADA / CARTERA BRUTA]
Index: []

[0 rows x 27 columns]

In [10]:
lista_balance=load.procesar_balances(load.archivos,load.meses, load.cuentas)
indicadores_balance=feature_engineering.calcular_variaciones_balance(lista_balance)

In [11]:
lista_balance[25].info()

<class 'pandas.DataFrame'>
Index: 24 entries, 0 to 25
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   MES                   24 non-null     str
 1   AÑO                   24 non-null     int64
 2   ENTIDAD               24 non-null     str
 3   FONDOS DISPONIBLES    24 non-null     float64
 4   INVERSIONES           24 non-null     float64
 5   CARTERA DE CRÉDITOS   24 non-null     float64
 6   TOTAL ACTIVO          24 non-null     float64
 7   Depósitos a la vista  24 non-null     float64
 8   Depósitos a plazo     24 non-null     float64
 9   TOTAL PATRIMONIO      24 non-null     float64
dtypes: float64(7), int64(1), str(2)
memory usage: 2.1 KB

In [12]:
indicadores_balance.columns.to_list()

['MES',
 'AÑO',
 'ENTIDAD',
 'VAR_FONDOS DISPONIBLES',
 'VAR_INVERSIONES',
 'VAR_CARTERA DE CRÉDITOS',
 'VAR_TOTAL ACTIVO',
 'VAR_Depósitos a la vista',
 'VAR_Depósitos a plazo',
 'VAR_TOTAL PATRIMONIO']

In [13]:
indicadores_balance

,MES,AÑO,ENTIDAD,VAR_FONDOS DISPONIBLES,VAR_INVERSIONES,VAR_CARTERA DE CRÉDITOS,VAR_TOTAL ACTIVO,VAR_Depósitos a la vista,VAR_Depósitos a plazo,VAR_TOTAL PATRIMONIO
0,Mayo,2022,BP GUAYAQUIL,-0.153575,-0.031059,0.219636,0.108500,0.144194,0.163349,0.080876
1,Mayo,2022,BP PACIFICO,-0.161024,0.152143,-0.006714,-0.002157,-0.037496,0.076166,0.020035
2,Mayo,2022,BP PICHINCHA,-0.345962,0.008894,0.341896,0.106841,0.090957,0.176605,0.043768
3,Mayo,2022,BP PRODUBANCO,-0.045015,-0.035218,0.241502,0.138065,0.092976,0.119563,0.077973
4,Mayo,2022,BP AUSTRO,-0.159378,0.069119,0.214098,0.114007,0.078231,0.048206,0.128133
...,...,...,...,...,...,...,...,...,...,...
1203,Julio,2026,BP CAPITAL,-0.017643,0.545330,0.434054,0.322436,0.046285,0.445646,0.040729
1204,Julio,2026,BP DELBANK,0.096224,-0.379255,-0.118974,-0.102445,-0.125425,-0.227068,0.051840
1205,Julio,2026,BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.,1.398896,0.509052,0.781038,0.712938,0.275121,1.096880,-0.056485
1206,Julio,2026,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",-0.585971,0.248656,0.036946,-0.051873,-0.138384,0.086575,0.067031
1207,Julio,2026,BP VISIONFUND ECUADOR S.A.,0.114965,0.669452,0.232972,0.232023,0.450468,0.703935,0.078424

In [14]:
dataset_final = dataset_indicadores_cartera.merge(
    indicadores_balance,
    on=["MES", "AÑO", "ENTIDAD"],
    how="left"
)

### Validación del dataset

In [15]:
dataset_final.shape

(1304, 34)

In [16]:
dataset_final = dataset_final[
    ~(
        (dataset_final["AÑO"] == 2022) &
        (dataset_final["MES"].isin(["Enero", "Febrero", "Marzo", "Abril"]))
    )
].copy()

In [17]:
dataset_final.shape

(1208, 34)

In [18]:
dataset_final

,MES,AÑO,ENTIDAD,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6),INDICE DE CAPITALIZACION NETO: FK / FI,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO,MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO,MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO,...,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,CARTERA REFINANCIADA / CARTERA BRUTA,CARTERA REESTRUCTURADA / CARTERA BRUTA,VAR_FONDOS DISPONIBLES,VAR_INVERSIONES,VAR_CARTERA DE CRÉDITOS,VAR_TOTAL ACTIVO,VAR_Depósitos a la vista,VAR_Depósitos a plazo,VAR_TOTAL PATRIMONIO
96,Mayo,2022,BP GUAYAQUIL,4.106345,0.081208,0.133465,0.866535,1.204264,0.015497,0.018206,...,0.007049,0.017101,0.005272,-0.153575,-0.031059,0.219636,0.108500,0.144194,0.163349,0.080876
97,Mayo,2022,BP PACIFICO,2.76007,0.095491,0.217156,0.782844,1.112745,0.032618,0.044019,...,0.017987,0.095438,0.041668,-0.161024,0.152143,-0.006714,-0.002157,-0.037496,0.076166,0.020035
98,Mayo,2022,BP PICHINCHA,-12.882069,0.087281,0.087276,0.912724,1.423879,0.02102,0.042779,...,0.017432,0.021698,0.047222,-0.345962,0.008894,0.341896,0.106841,0.090957,0.176605,0.043768
99,Mayo,2022,BP PRODUBANCO,3.457887,0.07046,0.119412,0.880588,1.46171,0.029096,0.02892,...,0.010628,0.006073,0.024845,-0.045015,-0.035218,0.241502,0.138065,0.092976,0.119563,0.077973
100,Mayo,2022,BP AUSTRO,1.295431,0.077153,0.160334,0.839666,1.042581,0.077468,0.016729,...,0.025212,0.070088,0.027836,-0.159378,0.069119,0.214098,0.114007,0.078231,0.048206,0.128133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,Julio,2026,BP CAPITAL,0.743608,0.088779,0.203118,0.796882,0.974991,0.035269,0,...,0.041185,0.014315,0.002475,-0.017643,0.545330,0.434054,0.322436,0.046285,0.445646,0.040729
1300,Julio,2026,BP DELBANK,7.435204,0.288765,0.157979,0.842021,1.769811,0.105913,0.000002,...,0.020171,0.068912,0.003849,0.096224,-0.379255,-0.118974,-0.102445,-0.125425,-0.227068,0.051840
1301,Julio,2026,BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.,0.788369,0.055191,0.128191,0.871809,0.96599,0.000358,0,...,0.012358,0.028839,0.007510,1.398896,0.509052,0.781038,0.712938,0.275121,1.096880,-0.056485
1302,Julio,2026,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",2.990621,0.103658,0.105249,0.894751,1.069191,0.079619,0.006083,...,0.058904,0.041134,0.006622,-0.585971,0.248656,0.036946,-0.051873,-0.138384,0.086575,0.067031
1303,Julio,2026,BP VISIONFUND ECUADOR S.A.,21.25641,0.128662,0.037131,0.962869,1.177842,0.008478,0,...,0.022598,0.007556,0.000656,0.114965,0.669452,0.232972,0.232023,0.450468,0.703935,0.078424

In [19]:
dataset_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1208 entries, 96 to 1303
Data columns (total 34 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   MES                                                                1208 non-null   str
 1   AÑO                                                                1208 non-null   int64
 2   ENTIDAD                                                            1208 non-null   object
 3   ( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6)  1208 non-null   object
 4   INDICE DE CAPITALIZACION NETO: FK / FI                             1208 non-null   object
 5   ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS                        1208 non-null   object
 6   ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS                                1208 non-null   object
 7   ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO                            1208 non-null   object
 8   MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO                        1208 non-null   object
 9   MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO                   1208 non-null   object
 10  MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO                   1208 non-null   object
 11  MOROSIDAD DE LA CARTERA TOTAL                                      1208 non-null   object
 12  COBERTURA DE LA CARTERA REFINANCIADA                               1208 non-null   object
 13  COBERTURA DE LA CARTERA REESTRUCTURADA                             1208 non-null   object
 14  COBERTURA DE LA CARTERA PROBLEMÁTICA                               1208 non-null   object
 15  GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO PROMEDIO (3)          1208 non-null   object
 16  GASTOS DE OPERACION  / MARGEN FINANCIERO                           1208 non-null   object
 17  GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3)                 1208 non-null   object
 18  RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO                     1208 non-null   object
 19  RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO                         1208 non-null   object
 20  CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO)         1208 non-null   object
 21  FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO                 1208 non-null   object
 22  CARTERA IMPRODUCTIVA / CARTERA BRUTA                               1207 non-null   float64
 23  CARTERA VENCIDA / CARTERA BRUTA                                    1207 non-null   float64
 24  CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA                   1207 non-null   float64
 25  CARTERA REFINANCIADA / CARTERA BRUTA                               1207 non-null   float64
 26  CARTERA REESTRUCTURADA / CARTERA BRUTA                             1207 non-null   float64
 27  VAR_FONDOS DISPONIBLES                                             1208 non-null   float64
 28  VAR_INVERSIONES                                                    1208 non-null   float64
 29  VAR_CARTERA DE CRÉDITOS                                            1208 non-null   float64
 30  VAR_TOTAL ACTIVO                                                   1208 non-null   float64
 31  VAR_Depósitos a la vista                                           1208 non-null   float64
 32  VAR_Depósitos a plazo                                              1208 non-null   float64
 33  VAR_TOTAL PATRIMONIO                                               1208 non-null   float64
dtypes: float64(12), int64(1), object(20), str(1)
memory usage: 321.0+ KB

In [20]:
dataset_final.iloc[:, 3:].dtypes

( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6)     object
INDICE DE CAPITALIZACION NETO: FK / FI                                object
ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS                           object
ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS                                   object
ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO                               object
MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO                           object
MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO                      object
MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO                      object
MOROSIDAD DE LA CARTERA TOTAL                                         object
COBERTURA DE LA CARTERA REFINANCIADA                                  object
COBERTURA DE LA CARTERA REESTRUCTURADA                                object
COBERTURA DE LA CARTERA PROBLEMÁTICA                                  object
GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO PROMEDIO (3)             object
GASTOS DE OPERACION  / MARGEN FINANCIERO                              object
GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3)                    object
RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO                        object
RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO                            object
CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO)            object
FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO                    object
CARTERA IMPRODUCTIVA / CARTERA BRUTA                                 float64
CARTERA VENCIDA / CARTERA BRUTA                                      float64
CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA                     float64
CARTERA REFINANCIADA / CARTERA BRUTA                                 float64
CARTERA REESTRUCTURADA / CARTERA BRUTA                               float64
VAR_FONDOS DISPONIBLES                                               float64
VAR_INVERSIONES                                                      float64
VAR_CARTERA DE CRÉDITOS                                              float64
VAR_TOTAL ACTIVO                                                     float64
VAR_Depósitos a la vista                                             float64
VAR_Depósitos a plazo                                                float64
VAR_TOTAL PATRIMONIO                                                 float64
dtype: object

In [21]:
columnas_numericas = [
    col for col in dataset_final.columns
    if col not in ["MES", "AÑO", "ENTIDAD"]
]

columnas_no_numericas = [ "MES", "AÑO", "ENTIDAD"]

In [22]:
columnas_no_numericas

['MES', 'AÑO', 'ENTIDAD']

In [23]:
dataset_final[columnas_numericas] = (
    dataset_final[columnas_numericas]
    .apply(pd.to_numeric, errors="coerce")
    .astype("float64")
)

In [24]:
dataset_final[columnas_no_numericas] = (
    dataset_final[columnas_no_numericas]
    .astype(str)
)

In [25]:
dataset_final.describe()

,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6),INDICE DE CAPITALIZACION NETO: FK / FI,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO,MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO,MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO,MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO,MOROSIDAD DE LA CARTERA TOTAL,COBERTURA DE LA CARTERA REFINANCIADA,...,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,CARTERA REFINANCIADA / CARTERA BRUTA,CARTERA REESTRUCTURADA / CARTERA BRUTA,VAR_FONDOS DISPONIBLES,VAR_INVERSIONES,VAR_CARTERA DE CRÉDITOS,VAR_TOTAL ACTIVO,VAR_Depósitos a la vista,VAR_Depósitos a plazo,VAR_TOTAL PATRIMONIO
count,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,...,1207.000000,1207.000000,1207.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000
mean,16.564382,0.113417,0.129656,0.870344,1.452182,0.049878,0.066555,0.089563,0.047017,1.040733,...,0.031721,0.036880,0.019650,0.114038,0.229692,0.099536,0.097517,0.190345,25.429884,0.058678
std,508.772993,0.096263,0.067545,0.067545,1.548236,0.039261,0.207324,0.125578,0.046990,1.290756,...,0.030505,0.035211,0.020487,0.452901,0.599447,0.194632,0.133781,0.655566,437.046749,0.135612
min,-1123.052066,-2.589472,-0.002645,0.583179,0.212959,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-0.731714,-0.761311,-1.000000,-0.884704,-0.684559,-1.000000,-0.772532
25%,0.884036,0.079909,0.085705,0.841721,1.059337,0.028479,0.000000,0.024433,0.023536,0.584152,...,0.016404,0.009921,0.004368,-0.124675,-0.086429,0.034203,0.029916,-0.030455,0.023584,0.013970
50%,2.636429,0.092059,0.115675,0.884325,1.140050,0.046086,0.014703,0.052714,0.034540,0.814337,...,0.024161,0.026232,0.013293,0.041677,0.137785,0.098010,0.091172,0.070587,0.119615,0.063610
75%,5.604946,0.142611,0.158279,0.914295,1.306533,0.062934,0.028413,0.112452,0.054207,1.058919,...,0.035671,0.054642,0.027514,0.236876,0.368646,0.155629,0.143349,0.224256,0.224212,0.103479
max,17606.001928,0.341963,0.416821,1.002645,23.509207,0.430763,1.000000,1.000000,0.313073,14.657317,...,0.205025,0.189812,0.116167,7.810275,4.724520,1.067010,0.849168,8.649531,9494.059333,1.048895

In [26]:
dataset_final[columnas_numericas] = (
    dataset_final[columnas_numericas] * 100
)

In [27]:
dataset_final.describe()

,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6),INDICE DE CAPITALIZACION NETO: FK / FI,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO,MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO,MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO,MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO,MOROSIDAD DE LA CARTERA TOTAL,COBERTURA DE LA CARTERA REFINANCIADA,...,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,CARTERA REFINANCIADA / CARTERA BRUTA,CARTERA REESTRUCTURADA / CARTERA BRUTA,VAR_FONDOS DISPONIBLES,VAR_INVERSIONES,VAR_CARTERA DE CRÉDITOS,VAR_TOTAL ACTIVO,VAR_Depósitos a la vista,VAR_Depósitos a plazo,VAR_TOTAL PATRIMONIO
count,1.208000e+03,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,...,1207.000000,1207.000000,1207.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000,1208.000000
mean,1.656438e+03,11.341694,12.965590,87.034410,145.218249,4.987763,6.655453,8.956287,4.701747,104.073253,...,3.172085,3.688033,1.964977,11.403789,22.969206,9.953627,9.751733,19.034497,2542.988363,5.867807
std,5.087730e+04,9.626256,6.754526,6.754526,154.823626,3.926121,20.732450,12.557807,4.699044,129.075563,...,3.050455,3.521125,2.048710,45.290140,59.944724,19.463239,13.378119,65.556642,43704.674888,13.561230
min,-1.123052e+05,-258.947223,-0.264501,58.317865,21.295925,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-73.171448,-76.131089,-100.000000,-88.470411,-68.455858,-100.000000,-77.253164
25%,8.840359e+01,7.990934,8.570496,84.172115,105.933679,2.847946,0.000000,2.443350,2.353552,58.415206,...,1.640437,0.992060,0.436808,-12.467466,-8.642882,3.420324,2.991587,-3.045542,2.358359,1.397009
50%,2.636429e+02,9.205931,11.567498,88.432502,114.004995,4.608605,1.470285,5.271447,3.453965,81.433699,...,2.416134,2.623152,1.329306,4.167747,13.778457,9.801012,9.117156,7.058723,11.961454,6.361039
75%,5.604946e+02,14.261135,15.827885,91.429504,130.653288,6.293386,2.841323,11.245163,5.420679,105.891938,...,3.567129,5.464191,2.751399,23.687607,36.864567,15.562938,14.334863,22.425626,22.421234,10.347918
max,1.760600e+06,34.196266,41.682135,100.264501,2350.920665,43.076268,100.000000,100.000000,31.307321,1465.731674,...,20.502539,18.981181,11.616699,781.027486,472.451991,106.701001,84.916787,864.953131,949405.933333,104.889489

In [28]:
dataset_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1208 entries, 96 to 1303
Data columns (total 34 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   MES                                                                1208 non-null   str
 1   AÑO                                                                1208 non-null   str
 2   ENTIDAD                                                            1208 non-null   str
 3   ( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6)  1208 non-null   float64
 4   INDICE DE CAPITALIZACION NETO: FK / FI                             1208 non-null   float64
 5   ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS                        1208 non-null   float64
 6   ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS                                1208 non-null   float64
 7   ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO                            1208 non-null   float64
 8   MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO                        1208 non-null   float64
 9   MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO                   1208 non-null   float64
 10  MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO                   1208 non-null   float64
 11  MOROSIDAD DE LA CARTERA TOTAL                                      1208 non-null   float64
 12  COBERTURA DE LA CARTERA REFINANCIADA                               1208 non-null   float64
 13  COBERTURA DE LA CARTERA REESTRUCTURADA                             1208 non-null   float64
 14  COBERTURA DE LA CARTERA PROBLEMÁTICA                               1208 non-null   float64
 15  GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO PROMEDIO (3)          1208 non-null   float64
 16  GASTOS DE OPERACION  / MARGEN FINANCIERO                           1208 non-null   float64
 17  GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3)                 1208 non-null   float64
 18  RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO                     1208 non-null   float64
 19  RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO                         1208 non-null   float64
 20  CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO)         1208 non-null   float64
 21  FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO                 1208 non-null   float64
 22  CARTERA IMPRODUCTIVA / CARTERA BRUTA                               1207 non-null   float64
 23  CARTERA VENCIDA / CARTERA BRUTA                                    1207 non-null   float64
 24  CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA                   1207 non-null   float64
 25  CARTERA REFINANCIADA / CARTERA BRUTA                               1207 non-null   float64
 26  CARTERA REESTRUCTURADA / CARTERA BRUTA                             1207 non-null   float64
 27  VAR_FONDOS DISPONIBLES                                             1208 non-null   float64
 28  VAR_INVERSIONES                                                    1208 non-null   float64
 29  VAR_CARTERA DE CRÉDITOS                                            1208 non-null   float64
 30  VAR_TOTAL ACTIVO                                                   1208 non-null   float64
 31  VAR_Depósitos a la vista                                           1208 non-null   float64
 32  VAR_Depósitos a plazo                                              1208 non-null   float64
 33  VAR_TOTAL PATRIMONIO                                               1208 non-null   float64
dtypes: float64(31), str(3)
memory usage: 321.0 KB

In [29]:
nulos = pd.DataFrame({
    "Variable": dataset_final.columns,
    "Cantidad_nulos": dataset_final.isna().sum().values,
    "Porcentaje_nulos": (
        dataset_final.isna().mean().values * 100
    )
})

nulos

,Variable,Cantidad_nulos,Porcentaje_nulos
0,MES,0,0.000000
1,AÑO,0,0.000000
2,ENTIDAD,0,0.000000
3,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILI...,0,0.000000
4,INDICE DE CAPITALIZACION NETO: FK / FI,0,0.000000
5,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,0,0.000000
6,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,0,0.000000
7,ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO,0,0.000000
8,MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO,0,0.000000
9,MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO,0,0.000000
10,MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO,0,0.000000
11,MOROSIDAD DE LA CARTERA TOTAL,0,0.000000
12,COBERTURA DE LA CARTERA REFINANCIADA,0,0.000000
13,COBERTURA DE LA CARTERA REESTRUCTURADA,0,0.000000
14,COBERTURA DE LA CARTERA PROBLEMÁTICA,0,0.000000
15,GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO P...,0,0.000000
16,GASTOS DE OPERACION / MARGEN FINANCIERO,0,0.000000
17,GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO...,0,0.000000
18,RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO,0,0.000000
19,RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO,0,0.000000
20,CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSI...,0,0.000000
21,FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO P...,0,0.000000
22,CARTERA IMPRODUCTIVA / CARTERA BRUTA,1,0.082781
23,CARTERA VENCIDA / CARTERA BRUTA,1,0.082781
24,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,1,0.082781
25,CARTERA REFINANCIADA / CARTERA BRUTA,1,0.082781
26,CARTERA REESTRUCTURADA / CARTERA BRUTA,1,0.082781
27,VAR_FONDOS DISPONIBLES,0,0.000000
28,VAR_INVERSIONES,0,0.000000
29,VAR_CARTERA DE CRÉDITOS,0,0.000000
30,VAR_TOTAL ACTIVO,0,0.000000
31,VAR_Depósitos a la vista,0,0.000000
32,VAR_Depósitos a plazo,0,0.000000
33,VAR_TOTAL PATRIMONIO,0,0.000000

In [30]:
nulos = nulos.sort_values(
    "Cantidad_nulos",
    ascending=False
).reset_index(drop=True)

nulos

,Variable,Cantidad_nulos,Porcentaje_nulos
0,CARTERA VENCIDA / CARTERA BRUTA,1,0.082781
1,CARTERA IMPRODUCTIVA / CARTERA BRUTA,1,0.082781
2,CARTERA REFINANCIADA / CARTERA BRUTA,1,0.082781
3,CARTERA REESTRUCTURADA / CARTERA BRUTA,1,0.082781
4,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,1,0.082781
5,MES,0,0.000000
6,AÑO,0,0.000000
7,ENTIDAD,0,0.000000
8,INDICE DE CAPITALIZACION NETO: FK / FI,0,0.000000
9,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILI...,0,0.000000
10,MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO,0,0.000000
11,MOROSIDAD DE LA CARTERA TOTAL,0,0.000000
12,COBERTURA DE LA CARTERA REFINANCIADA,0,0.000000
13,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,0,0.000000
14,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,0,0.000000
15,ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO,0,0.000000
16,MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO,0,0.000000
17,MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO,0,0.000000
18,GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO...,0,0.000000
19,GASTOS DE OPERACION / MARGEN FINANCIERO,0,0.000000
20,GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO P...,0,0.000000
21,COBERTURA DE LA CARTERA PROBLEMÁTICA,0,0.000000
22,COBERTURA DE LA CARTERA REESTRUCTURADA,0,0.000000
23,FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO P...,0,0.000000
24,RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO,0,0.000000
25,CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSI...,0,0.000000
26,RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO,0,0.000000
27,VAR_FONDOS DISPONIBLES,0,0.000000
28,VAR_INVERSIONES,0,0.000000
29,VAR_CARTERA DE CRÉDITOS,0,0.000000
30,VAR_TOTAL ACTIVO,0,0.000000
31,VAR_Depósitos a la vista,0,0.000000
32,VAR_Depósitos a plazo,0,0.000000
33,VAR_TOTAL PATRIMONIO,0,0.000000

In [31]:
columnas_con_un_nulo=["CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA"
,"CARTERA REFINANCIADA / CARTERA BRUTA"
,"CARTERA VENCIDA / CARTERA BRUTA"
,"CARTERA IMPRODUCTIVA / CARTERA BRUTA"
,"CARTERA REESTRUCTURADA / CARTERA BRUTA"]

In [32]:
dataset_final.loc[
    dataset_final[columnas_con_un_nulo].isna().any(axis=1),
    ["AÑO", "MES", "ENTIDAD"] + columnas_con_un_nulo
]

,AÑO,MES,ENTIDAD,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,CARTERA REFINANCIADA / CARTERA BRUTA,CARTERA VENCIDA / CARTERA BRUTA,CARTERA IMPRODUCTIVA / CARTERA BRUTA,CARTERA REESTRUCTURADA / CARTERA BRUTA
931,2025,Marzo,BP FINCA S.A./BANCO AMIBANK S.A.,NaN,NaN,NaN,NaN,NaN

In [33]:
dataset_final.shape

(1208, 34)

In [34]:
dataset_final = dataset_final[
    ~(
        (dataset_final["AÑO"] == "2025") &
        (dataset_final["MES"].str.strip() == "Marzo") &
        (dataset_final["ENTIDAD"] == "BP FINCA S.A./BANCO AMIBANK S.A.")
    )
].copy()

In [35]:
dataset_final.shape

(1207, 34)

### Detección de duplicados

In [36]:
def detectar_duplicados(df):
    return df.duplicated(
        subset=["AÑO", "MES", "ENTIDAD"]
    ).sum()

In [37]:
detectar_duplicados(dataset_final)

np.int64(0)

### Detección de infinitos en las variables numéricas

In [38]:
def detectar_infinitos(df):
    columnas_numericas = df.select_dtypes(
        include="number"
    ).columns

    return np.isinf(
        df[columnas_numericas]
    ).sum()

In [41]:
detectar_infinitos(dataset_final)

( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6)    0
INDICE DE CAPITALIZACION NETO: FK / FI                               0
ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS                          0
ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS                                  0
ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO                              0
MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO                          0
MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO                     0
MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO                     0
MOROSIDAD DE LA CARTERA TOTAL                                        0
COBERTURA DE LA CARTERA REFINANCIADA                                 0
COBERTURA DE LA CARTERA REESTRUCTURADA                               0
COBERTURA DE LA CARTERA PROBLEMÁTICA                                 0
GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO PROMEDIO (3)            0
GASTOS DE OPERACION  / MARGEN FINANCIERO                             0
GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3)                   0
RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO                       0
RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO                           0
CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO)           0
FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO                   0
CARTERA IMPRODUCTIVA / CARTERA BRUTA                                 0
CARTERA VENCIDA / CARTERA BRUTA                                      0
CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA                     0
CARTERA REFINANCIADA / CARTERA BRUTA                                 0
CARTERA REESTRUCTURADA / CARTERA BRUTA                               0
VAR_FONDOS DISPONIBLES                                               0
VAR_INVERSIONES                                                      0
VAR_CARTERA DE CRÉDITOS                                              0
VAR_TOTAL ACTIVO                                                     0
VAR_Depósitos a la vista                                             0
VAR_Depósitos a plazo                                                0
VAR_TOTAL PATRIMONIO                                                 0
dtype: int64

### Entidades consideradas

In [43]:
dataset_final["ENTIDAD"].unique()

<StringArray>
[                                           'BP GUAYAQUIL',
                                             'BP PACIFICO',
                                            'BP PICHINCHA',
                                           'BP PRODUBANCO',
                                               'BP AUSTRO',
                                          'BP BOLIVARIANO',
                                             'BP CITIBANK',
                                               'BP DINERS',
                                    'BP GENERAL RUMIÑAHUI',
                                        'BP INTERNACIONAL',
                                                 'BP LOJA',
                                              'BP MACHALA',
                                            'BP SOLIDARIO',
                                            'BP PROCREDIT',
                                             'BP AMAZONAS',
                            'BP BANCO COMERCIAL DE MANABI',
                                              'BP LITORAL',
                                         'BP COOPNACIONAL',
                                              'BP CAPITAL',
                        'BP FINCA S.A./BANCO AMIBANK S.A.',
                                              'BP DELBANK',
                     'BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.',
 'BP BANCO  DESARROLLO DE LOS PUEBLOS  S.A., CODESARROLLO',
                              'BP VISIONFUND ECUADOR S.A.']
Length: 24, dtype: str

In [44]:
base_final = dataset_final.copy()

In [47]:
base_final.to_excel("../data_processed/base_final.xlsx", index=False)

### Conclusiones:

1. Se logró integrar información de diferentes fuentes y años.
El flujo integra los indicadores, información de cartera y variaciones del balance para el período 2022–2026. Esto deja una base estructurada por AÑO, MES y ENTIDAD, que posteriormente permite comparar el comportamiento de cada banco a través del tiempo.
2. La información quedó estandarizada en variables numéricas, y se multiplicó por 100.
3. En el preprocessing conviertes las variables financieras a float64 y las variables categóricas (MES, AÑO, ENTIDAD) a texto. Esto es importante porque las fuentes originales son archivos Excel y pueden contener valores almacenados como texto. Además, en el feature engineering también conviertes explícitamente las variables financieras a numéricas usando errors="coerce".
Se identificaron y trataron valores nulos derivados de los indicadores de cartera.
Las variables de cartera se construyen dividiendo cada componente para CARTERA BRUTA. Cuando la cartera bruta es 0, el código reemplaza ese denominador por NaN, evitando realizar una división entre cero.
Por tanto, los nulos encontrados en esas variables no necesariamente representan datos faltantes originales; pueden ser consecuencia de que no existe un denominador válido para calcular el indicador.
4. Se detectó un registro que debía excluirse del análisis.
En el notebook identificas específicamente el registro correspondiente a marzo de 2025 de BP FINCA S.A./BANCO AMIBANK S.A. y posteriormente lo eliminas. Esto indica que durante la validación encontraste una observación que no debía formar parte del dataset final.
5. No existen duplicados utilizando la llave lógica del dataset: AÑO, MES y ENTIDAD como identificadores. Esto es adecuado porque, conceptualmente, debería existir una observación por banco para cada período mensual.
6. Se verificó la presencia de valores infinitos.
Incluyes explícitamente una revisión de inf y -inf en las variables numéricas. Esto es especialmente importante porque varias variables son ratios y podrían generar infinitos si un denominador fuera cero. No existen valores infinitos.
7. Se analizarán un total de 24 entidades financieras privadas desde Mayo 2021 a Julio 2026, período en el que el ente de control realizó un proceso de homologación de la información financiera para que los datos sean comparables en el tiempo